// JsFromRoutes CacheKey 744cc3537e6ffbde83aec3508b003a0b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/'),
}
