// JsFromRoutes CacheKey 3f9758cfd6e2a8dc15b7a2e957acaecf
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/organizations'),
  create: /* #__PURE__ */ definePathHelper('post', '/organizations'),
  new: /* #__PURE__ */ definePathHelper('get', '/organizations/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/organizations/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/organizations/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/organizations/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/organizations/:id'),
}
