// JsFromRoutes CacheKey 1fd8f77e553c6fd6eb4e952cb143e4a0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/up'),
}
